- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/tests/test_views.py
- wardenclyffe/mediathread/views.py
Switching over the main encoding path for mediathread (non-audio uploads) from PCP to ETS.
We were already submitting everything to S3/ETS in parallel anyway so basically, we just make `select_workflow()` only return workflows for audio uploads (thus never submitting a video upload to PCP), and then make sure that when the file has been transcoded, sent back to us, and we've copied it over from S3 up to CUNIX, we submit it to mediathread as WC normally would've done after getting the "done" signal from PCP.
> Switch main encoding to aws

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/mediathread/tasks.py
- wardenclyffe/mediathread/tests/test_views.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/templates/mediathread/mediathread.html
audio2 used to mean 'mp3 -> mp4' instead of just plain mp3 uploading.
That has become the only approach that mediathread ever uses now,
so there's no more need for the two paths.
keeping 'audio' as the preferred parameter/flag, but always sending
audio files through the mp3 -> mp4 workflow.
I've basically gone through the code and anywhere that used the distinction,
flattened it to go that way. Then the mediathread API part is changed
so it accepts either 'audio' or 'audio2' parameters for
backwards compatibility.
> merge audio and audio2

- wardenclyffe/mediathread/tasks.py
- wardenclyffe/mediathread/tests/test_tasks.py
trying to break up the mediathread submit task a bit to make it easier to get some test coverage on it, which it clearly needs.
> Mediathread task refactor

- wardenclyffe/main/views.py
Been encountering an issue where copy s3 to cunix operations aren't being
executed automatically by celery. looking through the logs, i see that celery
tries, but can't retrieve the associated file object. that means it's a race
condition where celery is running the operation too quickly before a db transaction
in the web view has committed.
That's not supposed to happen, since the method that sets up the operation
is decorated with @transaction.atomic() and we make a savepoint, which is explicitly
committed before the operation is handed off to celery.
Reading the docs closely, I *think* what's happening is that for the SNS response
view, I decorated the _notification helper method with transaction.atomic (since
it's the one doing all the db work) instead of the post() method. The …
> :bug: move transaction.atomic decorator to post handler

- wardenclyffe/cuit/views.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/settings_production.py
- wardenclyffe/settings_shared.py
- wardenclyffe/settings_staging.py
- wardenclyffe/youtube/views.py
Another approach to the transactions + celery issue.
After reading this carefully: https://realpython.com/blog/python/transaction-management-with-django-1-6/
I think I now understand what was going on.
First, we still had the old pre 1.6 transaction middleware running, which does
god knows what in a 1.6+ context.
Next, without that middleware running, the default behavior in Django is AUTOCOMMIT, which
means that each db query is wrapped in a transaction. That actually works
quite nicely for this particular case of Celery interaction, since
making sure that queries have been fully committed before the task is sent
to Celery is exactly what we want.
However, the rest of our code is still written under the assumption that each HTTP
request is wrapped in a transaction and will …
> :bug: django 1.6+ transaction overhaul. PMT #99080

- wardenclyffe/main/views.py
- wardenclyffe/mediathread/views.py
Turns out that decorating post() does nothing.
https://docs.djangoproject.com/en/1.7/topics/class-based-views/intro/\#decorating-the-class
> properly decorate CBVs with transaction.non_atomic_requests

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/cuit/broken_quicktime.html
- wardenclyffe/templates/main/bulk_file_operation.html
- wardenclyffe/templates/main/bulk_operation.html
- wardenclyffe/templates/main/bulk_surelink.html
- wardenclyffe/templates/main/file_filter.html
- wardenclyffe/templates/main/file_index.html
- wardenclyffe/templates/main/search.html
- wardenclyffe/urls.py
Once upon a time, we implemented a bulk operation interface for Wardenclyffe. I think the only time we ever actually used it was when Brian and I needed to pull 10,000 quicktime videos down from cunix and run them all through a special PCP workflow designed to fix an encoding bug. After that it was forgotten about and more or less disappeared from the UI.
Now we'd like to bring it back and make it a little more useful. We still need to really get the video team to help us understand what use cases actually exist, but to start with, we believe that they sometimes need to run a group of videos through another PCP workflow and they also sometimes need to get surelink embed codes for a whole batch of videos all at once.
So, first I updated the bulk submit to PCP part, then I switched the bulk …
> Bulk operation resurrection

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/mediathread/views.py
This changes the workflow for mediathread uploaded audio files to have them encoded locally,
then sent up to S3 and Elastic Transcoder as video files. This completely eliminates
Podcast Producer from Wardenclyffe.
This feature is behind a feature flag called 'encode_audio', which is currently turned off
in production. Once this code is deployed, we can turn that flag on for testing, verify that
the pipeline all works, then turn the flag on for the general public and start working on
removing the PCP specific code from Wardenclyffe.
> audio mp3 -> mp4 conversion. PMT #97710

- wardenclyffe/main/smoke.py
- wardenclyffe/settings_staging.py
The mp3 to mp4 encoding only works with the real ffmpeg, not avconv's fake version.
This adds a smoketest to make sure that whatever the FFMPEG_PATH setting
points at is the real deal.
The avconv version gives output like:
$ /usr/bin/ffmpeg -version
ffmpeg version 0.8.17-4:0.8.17-0ubuntu0.12.04.1, Copyright (c) 2000-2014 the Libav developers
built on Mar 16 2015 13:26:50 with gcc 4.6.3
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
ffmpeg 0.8.17-4:0.8.17-0ubuntu0.12.04.1
libavutil    51. 22. 3 / 51. 22. 3
libavcodec   53. 35. 0 / 53. 35. 0 …
> add smoketest to check for ffmpeg vs avconv

- wardenclyffe/main/management/commands/copy_images_to_s3.py
- wardenclyffe/main/tasks.py
- wardenclyffe/settings_production.py
- wardenclyffe/settings_shared.py
- wardenclyffe/settings_staging.py
First step of the process for moving poster/thumb images off of local disk and handing it all off to AWS. The amount of local disk space required for just holding thumbnails makes WC difficult to run on eg a smallish linode server. S3 is set up better to serve static files like this anyway. Going to S3 also lets us remove one more instance of  sorl.thumbnail.
This PR takes the first small steps:
* when images are created, it uploads a copy of each to S3 in the background, with the same relative path that we were storing it under locally.
* batch upload command to handle uploading all the existing images (I'll run this manually once this code makes it out).
Once these are in place and the batch command has been run, all existing images will have their counterparts on S3 and all new ones …
> Images to s3

- wardenclyffe/main/models.py
- wardenclyffe/templates/404.html
- wardenclyffe/templates/500.html
- wardenclyffe/templates/main/bulk_operation.html
- wardenclyffe/templates/main/bulk_surelink.html
- wardenclyffe/templates/main/collection.html
- wardenclyffe/templates/main/dashboard.html
- wardenclyffe/templates/main/file.html
- wardenclyffe/templates/main/index.html
- wardenclyffe/templates/main/search.html
- wardenclyffe/templates/main/slow_operations.html
- wardenclyffe/templates/main/uuid_search.html
- wardenclyffe/templates/main/video.html
Images are now all up on S3 in addition to local.
This cuts over all the images that appear in the WC web UI to use the S3 version instead of the local/sorl version.
A downside to this is that on pages where sorl was actually thumbnailing the image, we're now just loading the full-size and letting the browser scale it. That's not ideal, wasting some bandwidth and client-side CPU/memory, but since there aren't that many users hitting those parts of WC directly (just our video team), I think it's an acceptable tradeoff, at least for the time being. We can do some pre-scaling if it becomes an issue, but we might as well wait until we're entirely cut over to S3 to do that.
> display images from S3 instead of local/sorl

- wardenclyffe/main/tasks.py
- wardenclyffe/main/views.py
This whole area of elastic transcoder is not well documented, so this is a bit of a shot in the dark. So it's behind a waffle flag.
The pipeline is set up with the right output S3 bucket and the preset has settings for  thumbnail generation.
I *think* the way to trigger it to actually generate thumbs is by specifying the `ThumbnailPattern` with `{count}` somewhere in it. I haven't been able to find a single full example anywhere online though, so it's still a bit of a guess.
The documentation on the SNS notification format that they send back when the encoding is done (http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/notifications.html) also conveniently leaves out thumbnails. So it's also not obvious how we get information on what thumbs it actually created. So I'm …
> tell elastic transcoder to generate thumbnails

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/tests/thumbnail_pattern.json
- wardenclyffe/main/views.py
Videos transcoded by ET now also produce thumbs.
ET notifies us about them by putting a `thumbnailPattern` entry into the SNS notification it sends when the job completes.
That pattern is basically the one that we submitted when we created the job, so now we're left to search the images bucket to see how many it actually created and make the corresponding database entries for them.
> ET thumbs output

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
Working on decoupling WC tasks from the uploaded video file that's sitting
in the temp dir. It's more work to have each task pull the file down
from S3, do it's thing and then delete the temp file, but it lets us
separate the webserver from the celery worker and sets us up to
have users upload their files directly to S3 instead of going through
WC's webserver.
Here, basically, instead of kicking off the extract metadata job immediately on upload, using the temp file, we wait until the file has been saved to S3, then we trigger a version that pulls it back down from S3, does its work and deletes it.
Note that since this one and #92 both decrease the expected number of default tasks, there will be a conflict and/or test failure on line 409 of `wardenclyffe/main/tests/test_models.py` on …
> pull video down from s3 to extract metadata

- wardenclyffe/cuit/tasks.py
- wardenclyffe/cuit/views.py
- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/tasks.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/youtube/tasks.py
- wardenclyffe/youtube/views.py
Originally, I had ideas about how operations could be re-run with certain parameters
overrided. The implementation then kept the operation's default parameters separate
from the dict of params passed in on each task invocation. Ended up never needing that
distinction and instead have since had to deal with the complexity of some
tasks using the 'params' dict directly with others ignoring that and loading
them from the operation.
This eliminates the separate params, normalizing everything down to the JSON
version that we store on each Operation object.
> normalize param handling in operations.

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
Specifically, when it comes back from ET, we need to check if it's in the
public collection, and if so, upload it to the public directory
on the CUIT media server.
For now, it's basically hard-coded as to which collection is public
(defaulting to secure for anything else). In lieu of a more comprehensive
approach to configuring where things end up, this will have to do.
> :bug: if the video is uploaded to the public collection, put it in the public directory. PMT #97823

- wardenclyffe/main/migrations/0002_auto_20150604_0617.py
- wardenclyffe/main/models.py
- wardenclyffe/settings_shared.py
`CharField(max_length=100)` is apparently equivalent to what sorl was using under the hood to store the image path. So this migration has the nice property of eliminating the `sorl` specific field without actually making any changes to the database. Once this has gone through, we can think about making that field something more appropriate.
Note that sorl is still listed in `requirements.txt`, since earlier migration scripts still need to be able to import it, even if we are no longer using it. In the future we can go through and carefully excise mention of sorl from those migrations and fully remove it from the project.
> stop using sorl entirely

- wardenclyffe/settings_shared.py
collectstatic was failing to pickup the wardenclyffe/media directory. this fix was made manually to staging & production
> collectstatic fix

- wardenclyffe/templates/main/jquery.html
- wardenclyffe/templates/mediathread/mediathread.html
Load the SWF locally for now.
This is a short-term patch to get stuff working again while we work on just switching over to plupload, which doesn't have this issue.
> Uploadify hack. Fixes PMT #101551

- wardenclyffe/main/smoke.py
In theory, WC still uses PCP, but only on 'internal' functionality, ie, operations
that must be explicitly initiated by video team staff. It's no longer in use
for public facing functionality (mediathread uploads) and is on the slate
for complete removal in the coming months.
The PCP server has been so unreliable lately that I'm now ready to just pull the smoketest out
of WC. Ie, if PCP's down, I just don't care that much anymore.
> remove PCP/Kino smoketest

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
instead of processing the mp3 file directly, locally, it now
uploads the source mp3 to S3. then the audio encode operation
works by pulling that mp3 down from s3 to process.
this sounds backwards if you haven't been paying attention to the
ongoing wardenclyffe refactoring.
the real goal here is to make all operations not have any
assumptions about what might already be sitting on the local
filesystem; always pulling from S3 instead. this frees us up
to have the celery worker(s) on different machines than the
web worker. it also sets us up to switch to having users
upload directly to S3 without ever touching the filesystem on
the web app
> local audio encode pulls from s3. PMT #101560

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/tests/test_tasks.py
Especially with the AWS stuff, sometimes operations just timeout for reasons that are out of our control. We have manual 'rerun' buttons and the video team knows to use them. But Celery supports automatically retrying tasks, so let's see if Wardenclyffe can just do that for them.
I implemented it with an exponential backoff and it maxes out at 10 retries (2^10 seconds is about 17 minutes).
This is kind of a rough pass. I expect that as we see how this handles actual production uploads, we'll want to whitelist/blacklist various exceptions. Ie, the exceptions raised when AWS is just being flakey should always trigger a retry while exceptions indicating something is wrong with the uploaded file ought to always fail immediately instead of retrying.
> automatically retry operations

- wardenclyffe/main/tasks.py
It would be nice to be able to keep track of how often tasks get
retried, now many retries happen, and whether they are maxing out.
This adds a couple metrics to graphite/statsd for that. There's one
counter that for every retry that happens, one for when max_retries is
reached, and then individual 'retry_01', 'retry_02', etc counters so we
can get a sense of how many retries it takes to get an operation to
complete. I think these will be handy to graph and alert off of.
> graphite metrics for retries

- wardenclyffe/main/tasks.py
since we're handling it ourselves with exponential backoff, we need to
tell celery not to use its default of 3 retries.
> disable max_retries

- wardenclyffe/main/views.py
This sentry error:
https://sentry.ccnmtl.columbia.edu/sentry-internal/wardenclyffe/group/911/
seems to come from amazon occasionally sending duplicate SNS events and
triggering a race condition. (this can happen on this view since it's in
non-atomic request mode).
It's not frequent and doesn't break anything, and this doesn't totally
fix the issue, but it reduces the span between checking if the specified
`File` exists and working with it, so the race condition should at least
be less common.
> handle simultaneous SNS responses a little better

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/urls.py
- wardenclyffe/util/__init__.py
- wardenclyffe/util/tests.py
this is the first phase of implementing direct to S3 upload
functionality (PMT #93962). provides an s3 upload signing view, more or
less ripped straight from the DMT.
For now, it's not actually hooked up to anything in the front-end. That
will come next.
> add a sign s3 view

- wardenclyffe/main/views.py
I'd taken that out of the straight to s3 workflow reasoning that we no
longer had a source file on the filesystem.
It looks like the extract metadata task still expects it to exist though
so it can stash metadata on it.
Easy enough to put it back in.
Once we've moved everything to S3 upload only, it will probably be much
simpler to just have the extract metadata job create it itself instead
of relying on it to already have been created.
> make a source file object on s3 upload

- wardenclyffe/templates/main/s3upload.html
once users are going straight to s3, it doesn't make sense for WC to
have a drop-off directory feature. We'll need to completely rethink that
use-case for S3 (really, it should be simpler; the video team will just
have access to a designated bucket and decent tools to drop files there,
then we can build a fairly simple interface that works off the list of
files in that bucket)
> remove drop-off directory functionality on s3 upload

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/templates/main/batch_upload.html
- wardenclyffe/templates/main/single_upload.html
- wardenclyffe/templates/mediathread/mediathread.html
- wardenclyffe/urls.py
made an 's3upload' flag in wardencflyffe admin, currently disabled for
everyone.
this implements s3upload across all the forms (including batch uploads
and mediathread upload), toggled by that flag. So
once this is out, we can enable the flag for admins or individual users
to begin testing the full workflow.
> waffle flag for s3upload

- wardenclyffe/templates/main/batch_upload.html
- wardenclyffe/templates/mediathread/mediathread.html
keep forgetting that. conditionals and compressor leads to this:
https://sentry.ccnmtl.columbia.edu/sentry-internal/wardenclyffe/group/1030/
So, just load both JS files. Testing locally, they appear to not
interfere with each other.
> remove waffle flags from compress blocks

- wardenclyffe/templates/main/s3upload.html
- wardenclyffe/templates/main/single_upload.html
- wardenclyffe/templates/mediathread/mediathread.html
on the mediathread upload form, we actually know if they're supposed to
be uploading a video or an audio file and can limit accordingly. on the
regular upload, we don't necessarily know until we know which collection
they are uploading to, which we have no way of knowing yet, so we have
to allow both video and audio types.
> limit file uploads to video/audio

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/batch_upload.html
- wardenclyffe/templates/main/single_upload.html
Addressing:
https://sentry.ccnmtl.columbia.edu/sentry-internal/wardenclyffe/group/1043/
added some basic JS validation to keep the submit button on the batch
upload form disabled until both a collection has been selected and one
or more videos have been uploaded (to s3 or plupload).
> prevent batch upload without collection set

- wardenclyffe/main/models.py
- wardenclyffe/mediathread/tests/test_views.py
- wardenclyffe/mediathread/views.py
It's been on for months now and I don't see us needing to disable audio
encoding in a hurry, so I think we can get rid of that code path.
Once this is merged, someone should then go into WC's admin and delete
the flag.
> remove the `encode_audio` waffle flag

- wardenclyffe/youtube/util.py
revert a previous refactoring that broke some of the retry logic on resumable youtube uploads.
> Youtube upload retry bugfix

- wardenclyffe/graphite/tests/__init__.py
- wardenclyffe/main/tests/__init__.py
- wardenclyffe/mediathread/tests/__init__.py
- wardenclyffe/youtube/tests/__init__.py
don't need to manually import tests like that anymore
> remove imports from test __init__.py files

- wardenclyffe/drop/urls.py
- wardenclyffe/drop/views.py
- wardenclyffe/urls.py
This is purely for information gathering. When SNS sends a message to
this endpoint, it just reads in the request and emails it to me so I can
see what they are sending.
The eventual goal is to create an SNS topic that passes along events
when files are uploaded to the S3 drop bucket, then to subscribe this
URL to that SNS topic.
What I discovered previously, doing SNS subscriptions on the elastic
transcoder workflow was that the AWS documentation is thin and confusing
when it comes to the exact format of the message payload that they send
you. The simplest approach is just to put something like this up and
trigger a few events and just see what you get back and figure out from
there what headers and message fields are actually useful for
identifying and routing.
So this whole view as it …
> dropbox SNS debug view

- wardenclyffe/drop/tasks.py
Apparently, boto.s3.bucket.copy_key() expects the (string) name of the
target bucket as parameter rather than a bucket object.
> copy_key() parameter fix

- wardenclyffe/util/mail.py
SES doesn't like 'ccnmtl-mediathread@columbia.edu'. change it to a
.ccnmtl.columbia.edu address.
> change mediathread from email address

- wardenclyffe/streamlogs/models.py
- wardenclyffe/streamlogs/tests/test_models.py
- wardenclyffe/templates/streamlogs/streamlog_detail.html
- wardenclyffe/urls.py
We have the filename in the `StreamLog` entry. If the video was uploaded
through WC, there will be a `File` somewhere with that filename, which
we can use to provide a link back to the `Video` entry.
> link StreamLogs back to matching Video

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/video.html
- wardenclyffe/urls.py
Adds a "flv to mp4" button on videos that have an attached flv, but no mp4. that will kick off a conversion for that one video.
Mostly, we want to be doing conversions in batch operations but this is a good place to start, and the functionality here will be needed in batch mode anyway.
> Flv to mp4 single video conversion

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/views.py
Some of the flvs do have an original source S3 file already up
there. For these, there's no need to pull the flv file down off cunix
and upload that to S3. The encoding should also come out better since
it's re-encoding from the original source instead of transcoding.
> optimize flv conversion when there's already an S3

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/templates/main/video.html
when you're viewing a video detail page, if there are corresponding
streamlogs for that video, show them.
> link videos back to streamlogs

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/tasks.py
After performing an FLV -> MP4 conversion, if the video has an associated Mediathread asset, we send a POST over there to inform it of the new URL.
The update logic does not yet exist on the Mediathread side, so it will need to be implemented before we can turn this feature on (it's behind a waffle switch).
The new bits in `wardenclyffe/mediathread/tasks.py` will be useful for looking at to implement that.
As it is currently implemented:
* it gets the mediathread asset URL, eg `https://mediathread.ccnmtl.columbia.edu/asset/1234/`, sticks `update/` on the end and makes a `POST` request there
* the parameters in that request roughly mirror the params that are sent to `/save/` when a new video is created, but stripped down to only the fields that would change as a result of the conversion …
> Mediathread replace

- wardenclyffe/mediathread/tasks.py
* Update post url to something more generic. Mediathread requires course awareness for urls that begin with /asset/
* Instead, include the asset-url in the post parameters.
> Mediathread replace 2

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/video_s3serve.html
- wardenclyffe/urls.py
Beginning to play around with pointing a player straight at the encoded
video on S3.
S3 does "pseudo-streaming" with range headers basically the same as our
FLV solution does, so this could potentially be "good enough" from a
performance perspective.
Right now, just instantiating a video.js player that loads the S3
URL (signed with a 1-hour expiration).
I'll also want to play around with setting up a cloudfront distribution
in front of it to see if that changes things. I think I can also
restrict based on IP address, so that's worth investigating.
I also plan on making an iframe-able version of this with a similar auth
scheme to surelink. Ie, a proof of concept with WC+S3 as the secure
streaming video server. If it seems workable, we can split it out into
its own service.
For now, this is …
> add s3serve view

- wardenclyffe/main/models.py
see discussion on #108425
With the FLV conversions, it's now possible for a Video to have multiple
CUIT Files associated with it. The code had been assuming that the first
one returned by the database was the only one (previously perhaps not a
totally valid assumption, but almost always correct, so we didn't run
into it).
This should now work with multiple Files that match; returning the
expected value if any of them match the criteria.
I wish I had some good test cases for these, but I'm not sure how to emulate the arbitrary ordering of queryset results in a test. These methods all have existing tests though, so this should uphold any existing expected behaviour.
> Stream multiple files fix

- wardenclyffe/main/models.py
ensure that the video has not only been processed, but has made it up to
cunix before trying to update the mediathread entry
> move update mediathread operation after s3 to cunix

- wardenclyffe/main/management/commands/meth_flv_to_mp4.py
manage command to run bulk flv -> mp4 conversions for mediathread
videos.
this seems like the simplest way to go about it. Just run the command
starting with a small number of conversions, check that they've run ok,
then run it again with a larger 'n'. Keep bumping it up until we run
into scaling issues or we've encoded all of the elligible videos.
> meth flv convert command

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/mediathread/tasks.py
If we update the mediathread asset but mediathread responds with a 404,
that's ok. It just means our link is outdated, so we can clear it out.
> handle 404s on update mediathread

- wardenclyffe/main/management/commands/import_flv_and_convert.py
All the FLVs that WC knew about have been converted, but we're still
seeing some FLVs being played that WC knows nothing about.
This should allow me to manually import FLV files from CUNIX one at a
time. I can just run the manage command and it creates a Video object,
then kicks off the flv -> mp4 conversion process as if it had happened
through the web.
Once I've done a few this way, I'll convert it to a view with a little
form so it can be done entirely through the web.
Eventually, I want to make it automatically triggered whenever WC sees
an unknown FLV played.
> manage command for manually importing an flv

- wardenclyffe/main/management/commands/import_flv_and_convert.py
just make it so I don't have to type in the full path of the flv
filename and can instead copy in the filename as it comes in from the
streamlogs. (also makes the title of the video a little less obnoxious)
> simplify flv filename handling a bit

- wardenclyffe/main/models.py
this still has to happen on the flv -> mp4 conversions, especially if
the video is ever going to make it up to mediathread.
So, after uploading to s3, we just check whether there is already a
source file attached to the video. if not, we know we need to extract
metadata.
> extract metadata after upload to s3

- wardenclyffe/main/models.py
`make_pull_from_s3_...` returns a single operation rather than a list
and `.extend()` is expecting a list. This was leading to some orphaned
operations.
> Post ops fix

- wardenclyffe/templates/streamlogs/streamlog_list.html
if the streamed file has a corresponding video in WC, link directly to
it from the streamlog list page. This will make it one step faster to
work through the remainder FLVs.
> link directly to videos on streamlog list

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/settings_production.py
- wardenclyffe/settings_shared.py
- wardenclyffe/templates/streamlogs/streamlog_list.html
- wardenclyffe/urls.py
basically just took the manage command and exposed it as a button on the
streamlog list page. So we can pull up the list, have a direct link to
the video if it is already in WC, or press a button to do the import if
it isn't.
> simple interface to import flvs directly from streamlog list

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
fixes this sentry issue:
https://sentry.io/columbia-ctl/wardenclyffe/issues/188955142/
which appears to be due to the user entering '480-' in a textbox instead
of just '480'. Ideally, this would be caught on the client side, but
since this is mostly an internal tool, I think it's fine to just strip
out anything non-numeric that comes in.
> strip out stray characters from surelink dimensions

- wardenclyffe/main/models.py
when WC was originally written, we were playing around with inline
doctests. The current test runner doesn't execute them though so they
don't really serve any purpose anymore. In particular, since they are
pretty much all on relatively trivial methods, they also aren't really
helping with understandability either. So currently they are just noise
and should probably be removed.
> remove vestigial doctests

- wardenclyffe/main/tasks.py
sentry: https://sentry.io/columbia-ctl/wardenclyffe/issues/193285033/
This splits out the retrieval of the Operation object from processing it. The exception we see in Sentry is happening because the `Operation.objects.get()` is raising the exception, so `operation` doesn't yet exist when it gets to the catch.
This should fix the exact exception we saw in Sentry there, though it doesn't really address the root issue. The `UnboundLocalError` is masking the real problem though, so we need to deal with it to see what's actually going wrong (basically, somewhere in the code, an Operation object is being passed in instead of an integer id).
> Fix unboundlocalerror sentry 193285033

- wardenclyffe/mediathread/views.py
for sentry:
https://sentry.io/columbia-ctl/wardenclyffe/issues/208551809/
`get_or_create()` should be atomic.
> atomic user creation. PMT #109791

- .gitignore
- Dockerfile
python 'cryptography' library won't install without it.
> include libffi-dev in docker build

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/file.html
- wardenclyffe/urls.py
see PMT #110468
the eventual goal is to allow Mediathread to delete old files from cunix
when removing old courses. As a first step, we implement a manual delete
from cunix function so we can at least test and make sure that works
properly before setting up an API that mediathread can access.
> delete file from CUNIX

- wardenclyffe/main/views.py
- wardenclyffe/mediathread/auth.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/urls.py
next step on PMT #110468
This exposes an API endpoint that mediathread can make a POST request to
when it wants to tell WC to delete a file off cunix.
We already have an auth setup for mediathread integration, so I re-used
that as much as possible for this endpoint. Since it's a slightly
different use-case, it's a little bit odd though, with a field
overloaded to have a different meaning.
The usual meth -> WC handoff is for a user going through the browser, so
the username and a post-upload redirect_to parameter is included in the
hmac.
The deletion would be happening from the backend, invisible to the user,
but the token approach is still useful, so we keep it. But instead of
using `redirect_to` as a location to send to afterwards, we just re-use
that field to hold the WC `video_id` of …
> expose API for cunix deletion

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/tasks.py
- wardenclyffe/mediathread/tests/test_tasks.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/panopto/tasks.py
- wardenclyffe/templates/mediathread/mediathread.html
This PR sets up an alternative upload path to the Panopto system. If Mediathread passes over a Panopto folder uuid, Wardenclyffe will now push the file over to Panopto rather than the h264 streaming server.
> Integrate Mediathread upload with Panopto

- wardenclyffe/templates/base.html
This fixes an issue in Chrome where these `<a>` tags have the wrong
cursor when hovering over them, because there's no href attribute.
> Fix cursor icon on dropdown buttons

- requirements.txt
- wardenclyffe/main/views.py
- wardenclyffe/settings_shared.py
- wardenclyffe/streamlogs/models.py
- wardenclyffe/streamlogs/tests/test_models.py
If a passed filename does not match perfectly, there's the possibility for multiple Panopto migrations to be requested. Adding two things to help:
* Add a match to the cunix "secure" directory
* Before submitting a "new" filename for conversion, see if there are any "similar" existing videos. If there are, don't go forward with the conversion.
> Surelink Video conversion: handle possible duplications

- wardenclyffe/mediathread/tasks.py
- wardenclyffe/panopto/views.py
- wardenclyffe/urls.py
Create a workflow to allow applications like Mediathread to kick off a media conversion.
> Panopto Conversion endpoint

- wardenclyffe/streamlogs/templatetags/streamlog_tags.py
- wardenclyffe/streamlogs/tests/test_views.py
- wardenclyffe/streamlogs/urls.py
- wardenclyffe/streamlogs/views.py
- wardenclyffe/templates/streamlogs/streamlog_detail.html
- wardenclyffe/templates/streamlogs/streamlog_list.html
Rather than just display lists and lists of StreamLogs, this PR modifies the StreamLog views to aggregate similar log material and provide counts. This should help us more easily identify media that is being used and needs to be migrated versus singular hits. The underlying detail view now shows the more granular information such as referer and user-agent.
> StreamLog - tuning view to be more useful

- wardenclyffe/panopto/tasks.py
When attempting to pull a thumbnail from Panopto, simply look in the url for "no_thumbnail" rather than a distinct file type. Panopto recently changed this to an .svg.
> Fix Panopto pull thumbnail task

- wardenclyffe/panopto/tasks.py
Panopto jobs sometimes become wedged and never return a proper status. Put in an override to the verify job that will allow us to manually create the (successful) Panopto file and let the full flow continue.
> Handle wedged Panopto job

- .travis.yml
- requirements.txt
This library shouldn't be installed on newer versions of python.
https://github.com/django-extensions/django-extensions/blob/master/setup.py#L125
> Don't install typing on python >= 3.5

- .travis.yml
I'm migrating wardenclyffe to ubuntu 18, so we don't need to test on py2.7.6 anymore.
> travis: remove py2.7.6 testing

- requirements.txt
Apparently this library is deprecated, and we should upgrade to
google-auth and oauthlib: https://github.com/googleapis/oauth2client
> :arrow_up: oauth2client 4.1.3

- requirements.txt
Note: this will also pull in the 1.7.0 changes because it looks like wardenclyffe was still on 1.6.0:
* Add XFrameOptionsMiddleware
* Add SecurityMiddleware
* Flag CSRF and Session cookie as secure
* Flag CSRF and Session cookie as http only
> :arrow_up: ccnmtlsettings 1.8.0

- wardenclyffe/main/models.py
This fixes an error on python 3.9:
AttributeError: module 'base64' has no attribute 'encodestring'
base64.encodestring() is deprecated since 3.9:
https://docs.python.org/3.8/library/base64.html#base64.encodestring
> Use base64.encodebytes() instead of encodestring()

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/admin/login.html
- wardenclyffe/templates/main/surelink_video.html
This PR remove the final piece of the Surelink authenticated streaming service. Videos that were already converted will still be proxied. Conversion is no longer possible due to tightened CUNIX security.
> Remove Surelink automatic conversion

- wardenclyffe/graphite/models.py
- wardenclyffe/graphite/tasks.py
The AWS management console does a very nice job at this. No need to add a graphite metric too.
This will resolve the need to update this code to boto3 as well.
> Remove weekly s3 storage report

- wardenclyffe/settings_shared.py
See: https://docs.celeryq.dev/en/v4.4.7/userguide/routing.html#automatic-routing
I don't think this custom MyRouter class is necessary, as routing can be handled within celery automatically.
Additionally, I don't think we need to define the exchange/exchange type manually - this should all be handled automatically on queue creation.
> Update CELERY_TASK_ROUTES to use automatic routing

- requirements.txt
When running the `./ve/bin/celery` command, I found that prompt_toolkit is required, as well as vine/amqp updates.
> Dependency fixes for celery 5

- requirements.txt
This fixes a build failure for me on python 3.12. See: https://github.com/roy-ht/editdistance/issues/94
> Use github release of editdistance 0.6.2

- wardenclyffe/main/tests/test_views.py
"assertEquals" is deprecated in newer versions of python.
> Fix tests with assertEqual

- wardenclyffe/mediathread/tests/test_views.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/templates/mediathread/mediathread.html
- wardenclyffe/urls.py
This view was split into two different function views, causing some weirdness with CSRF verification. I think it's best to just make this a more standard class-based view.
> Refactor Mediathread video upload form view

- wardenclyffe/settings_production.py
- wardenclyffe/settings_staging.py
For some reason, wardenclyffe was set up to use an old, manually-compiled ffmpeg distributed with salt. This seems unnecessary so I've gotten rid of that, and just used ubuntu's ffmpeg.
> Update ffmpeg path
