- wardenclyffe/cuit/views.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/youtube/views.py
in preparation for django 1.7, which no longer supports the old style.
> convert transactions to django 1.6+ style

- wardenclyffe/main/models.py
- wardenclyffe/mediathread/views.py
remove a lot of repetition around creating Operations.
> extract make_op() method

- wardenclyffe/mediathread/tasks.py
Removing the deprecated "mp3" primary source in favor of defaulting all audio to "mp4_audio" and all its parameters.
> Audio primarysource fix

- wardenclyffe/mediathread/tasks.py
regression introduced here: https://github.com/ccnmtl/wardenclyffe/commit/05ed5b0284821b956e51cf8cac0d3880a08b50ef
> fix mediathread video submission bug

- wardenclyffe/mediathread/views.py
the mediathread submit process needs a special entry with the parameters. The
interface for letting someone send an existing WC video to mediathread was
not creating that entry like the regular upload process.
Also realized that those need to be marked as non atomic while we're at it.
> :bug: fix post-facto mediathread submit PMT #99436

- media/css/main.css
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/index.html
This is just to avoid some confusion.. because this template
is actually showing all the collections, not just 'recent' ones.
> Change wording from 'recent collections' to 'all collections'

- wardenclyffe/mediathread/views.py
https://sentry.ccnmtl.columbia.edu/sentry-internal/wardenclyffe/group/711/
> Fix 500 error on Meth > Wardenclyffe upload

- wardenclyffe/main/tests/test_views.py
> remove s3_to_cunix flag from test

- wardenclyffe/main/views.py
> don't need to log full ET response anymore

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
More cleanly extensible approach to wiring up post-process hooks on operations.
> Post process hooks refactoring

- wardenclyffe/mediathread/views.py
- wardenclyffe/templates/mediathread/mediathread_plupload.html
It's behind the 'plupload' waffle flag.
> Plupload form for mediathread. PMT #101559

- wardenclyffe/templates/base.html
- wardenclyffe/templates/main/dashboard.html
- wardenclyffe/templates/main/plupload.html
- wardenclyffe/templates/main/upload.html
- wardenclyffe/templates/mediathread/mediathread_plupload.html
S3 and cloudfront serving works much better when compress is handling everything.
> use django-compressor more consistently

- requirements.txt
> remove zencoder lib

- requirements.txt
- wardenclyffe/settings_shared.py
> remove django-smartif

- requirements.txt
- wardenclyffe/settings_shared.py
> remove tagging

- requirements.txt
- wardenclyffe/settings_shared.py
> remove template_utils

- wardenclyffe/main/tasks.py
See PMT #103286.
We still ought to find out what the root cause of the issue is, but this
should be a useful band-aid for it.
> chmod 644 video files uploaded to CUIT

- wardenclyffe/main/models.py
doesn't necessarily indicate failure anymore.
> handle operations that return messages

- .gitignore
celery leaves some cruft in the current directory when you run it
> ignore celerybeat-schedule

- wardenclyffe/main/tasks.py
- wardenclyffe/settings_shared.py
don't hardcode it in there; make it a setting
> max retries setting

- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/video.html
- wardenclyffe/urls.py
- wardenclyffe/youtube/tasks.py
Form is behind the 's3_to_youtube' waffle flag.
> Pull from S3 and upload to Youtube. PMT #96957

- Makefile
- wardenclyffe/main/views.py
get cyclomatic complexity down to 9
> Complexity 9

- media/js/libs/s3upload.js
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/s3upload.html
- wardenclyffe/urls.py
This is in parallel to the regular upload form so we can start testing
it in production against the real AWS/EC2 setup.
There are still some big missing pieces like audio workflow and upload
to youtube, but this should be enough that we can sanity check the
general approach.
> direct to s3 upload form

- wardenclyffe/mediathread/views.py
OK, it turns out the audio workflow on a mediathread
upload is slightly different than a regular audio upload.
Instead of directly queueing up the tasks that would normally happen
after the S3 upload completes (extract metadata, and create ET job), we
instead trigger the audio encode (the "local audio encode" task is
poorly named, it does actually pull from S3 first). When that completes
it will trigger an S3 upload (of the generated mp4), which in turn will
trigger the normal tasks.
So when we got an audio upload for mediathread, we were queueing up
those other tasks immediately, with the .mp3 file as the
source. Instead, they need to wait until there's an .mp4 ready.
> fix audio workflow for mediathread s3 upload

- wardenclyffe/main/views.py
make the normal upload path (well, through s3 at least) take exactly the
same approach to audio processing as the mediathread one. Ie, force the
audio encode task first, rather than kicking off the ET and metadata
extraction tasks on the uploaded file (which is an mp3, not video).
This also should ensure that audio to video conversions get the correct
poster frame, taking care of the last bit of PMT #97710
> normalize audio handling

- requirements.txt
> remove dependency on urllib3

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_tasks.py
not used anymore since ET does all the frame extraction now.
> remove `make_images` task

- wardenclyffe/templates/main/youtube.html
- wardenclyffe/youtube/tests/test_views.py
- wardenclyffe/youtube/views.py
the upload to youtube functionality was still using uploadify and saving
to local disk
> upload to youtube via S3

- wardenclyffe/main/views.py
found another old, unused view that can be cleaned out
> remove save_file_locally()

- requirements.txt
- wardenclyffe/mediathread/tasks.py
- wardenclyffe/mediathread/views.py
> remove restclient

- Makefile
- wardenclyffe/main/models.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/main/views.py
- wardenclyffe/mediathread/tests/test_views.py
- wardenclyffe/mediathread/views.py
- wardenclyffe/urls.py
- wardenclyffe/youtube/util.py
some refactoring and test improvements.
> Refactoring 2014 06 24

- wardenclyffe/drop/snsparser.py
- wardenclyffe/drop/tests/sample_message.txt
- wardenclyffe/drop/tests/test_snsparser.py
with tests based on sample message
> SNS Message parser helper class

- wardenclyffe/drop/snsparser.py
- wardenclyffe/drop/tasks.py
- wardenclyffe/drop/tests/test_snsparser.py
- wardenclyffe/drop/tests/test_views.py
- wardenclyffe/drop/views.py
- wardenclyffe/main/models.py
- wardenclyffe/settings_shared.py
Add the view to listen for SNS events on the S3 dropbox bucket and respond by copying the uploaded file into the regular uploads bucket and kicking off the encoding pipeline.
> S3 dropbox view

- doc/banzai.md
writing a design document for some overhauling of the wardenclyffe workflow model
> WIP: banzai design document

- wardenclyffe/mediathread/views.py
sentry: https://sentry.ccnmtl.columbia.edu/sentry-internal/wardenclyffe/group/1145/
> fix 500 error on mediathread course listing

- wardenclyffe/streamlogs/models.py
- wardenclyffe/streamlogs/urls.py
- wardenclyffe/templates/streamlogs/streamlog_detail.html
- wardenclyffe/templates/streamlogs/streamlog_list.html
very basic views for seeing the flv streaming logs that have gone in. just a quick list and detail to start with.
> Streamlogs basic views

- wardenclyffe/streamlogs/models.py
- wardenclyffe/streamlogs/tests/test_views.py
- wardenclyffe/streamlogs/urls.py
- wardenclyffe/streamlogs/views.py
- wardenclyffe/templates/streamlogs/report.html
just a highcharts graph of streams per day for the last 30 days so far,
but we can add more to it later.
> add basic streamlogs graph/report

- wardenclyffe/streamlogs/urls.py
- wardenclyffe/streamlogs/views.py
we have more than 30 days of data now, so let's bump up the streamlogs graph to 100 days
> Streamlogs report 100

- wardenclyffe/main/views.py
avoid the usual race-condition
> non_atomic_requests on flv convert view

- wardenclyffe/main/tasks.py
if the view that created the operation didn't commit before calling
`.delay()` and the celery worker gets to it quickly, they `Operation`
object may not be in the database.
Ideally, the view would be careful to use
`@transaction.non_atomic_requests` and/or commit transactions
explicitly, but that's easy to miss.
We already have a retry with exponential backoff mechanism for
operations; this is actually the sort of thing that that should handle
quite well, so we might as well use it for this case as well.
> retry operation on a DoesNotExist

- wardenclyffe/templates/base.html
Hopefully this will get us some tracebacks and visibility on user upload
errors that are happening between the browser and S3.
> add Sentry/Raven JS

- Makefile
- wardenclyffe/main/tasks.py
- wardenclyffe/main/views.py
- wardenclyffe/youtube/util.py
> Complexity 5

- wardenclyffe/main/forms.py
- wardenclyffe/main/models.py
just a wee little refactoring to pull some modelforms out into
`forms.py` where they belong.
> extract form classes

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
- wardenclyffe/settings_production.py
> import public flv into public collection

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
for PMT #109135
need to be able to handle the mp4 files that are being streamed by the
flv server.
> handle strange case of flv import for mp4s

- wardenclyffe/streamlogs/urls.py
- wardenclyffe/streamlogs/views.py
- wardenclyffe/templates/streamlogs/report.html
we now have more than 100 days of data to display
> bump the streamlog report up to 200 days

- wardenclyffe/mediathread/views.py
PMT #95619
not being used any more.
> remove audio2 parameter

- wardenclyffe/templates/main/stats.html
switch over to our graphite server
> update metrics for stats page

- wardenclyffe/youtube/views.py
same refactoring, same mistake...
> missing parameter

- .bandit
- django.mk
- package-lock.json
- requirements.txt
- wardenclyffe/main/management/commands/create_posters.py
- wardenclyffe/main/smoke.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/tests/test_models.py
- wardenclyffe/settings_shared.py
- wardenclyffe/youtube/util.py
* ignoring numerous false positives
> bandit: python security linting

- .eslintrc.js
- package-lock.json
Closer to our previous jshint/jscs rules.
> Additional ESLint rules

- media/css/main.css
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/pagination.html
- wardenclyffe/templates/main/search.html
- wardenclyffe/urls.py
* add default view with all videos
* add additional columns - video extension, file location, tags
* sort by title
> Enhance Search View

- wardenclyffe/main/management/commands/inventory.py
Very simple job to parse and ingest directory listings from CUNIX.
> Inventory job: ingest directory listings

- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/upload.html
For the moment, the panopto upload choice will simply make a backup from s3 to cunix.
Very much missing @thraxil's wisdom and guidance on this effort.
>  Panopto integration - adding panopto option to the upload flow

- package-lock.json
- requirements.txt
- wardenclyffe/main/models.py
- wardenclyffe/main/tasks.py
- wardenclyffe/main/views.py
- wardenclyffe/panopto/tasks.py
- wardenclyffe/panopto/views.py
- wardenclyffe/templates/main/upload.html
- wardenclyffe/templates/panopto/manifest.xml
This pull request relocates the bulk of the panopto upload logic into the [pypanopto](https://github.com/ccnmtl/pypanopto) library. And, adds a task to asynchronously verify the upload status.
>  Panopto framework integration, part 2

- media/css/wardenclyffe.css
- wardenclyffe/templates/main/index.html
This PR begins a long-term UI interaction refactoring to make Wardenclyffe a focal point in our video asset management workflow.
> Homepage: make the base view more collection-centric

- package-lock.json
- wardenclyffe/graphite/tasks.py
Per [celery doc](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules), execute every three hours: midnight, 3am, 6am, 9am, noon, 3pm, 6pm, 9pm.
> Wardenclyffe S3 usage: run every three hours

- requirements.txt
- wardenclyffe/panopto/forms.py
- wardenclyffe/panopto/urls.py
- wardenclyffe/panopto/views.py
- wardenclyffe/settings_shared.py
- wardenclyffe/templates/base.html
- wardenclyffe/templates/main/collection.html
- wardenclyffe/templates/panopto/collection_submit.html
- wardenclyffe/templates/panopto/collection_submit_success.html
- wardenclyffe/urls.py
Upload a collection of media to the Panopto server. This is waffled at the moment so testing can be completed against staging before flipping over to the production server.
> Collection upload to Panopto

- wardenclyffe/main/tests/factories.py
- wardenclyffe/main/tests/test_views.py
- wardenclyffe/streamlogs/tests/test_views.py
- wardenclyffe/streamlogs/urls.py
- wardenclyffe/streamlogs/views.py
- wardenclyffe/templates/streamlogs/report.html
- wardenclyffe/templates/streamlogs/streamlog_list.html
* standard pagination
* standard keyword search
* view tests
> Streamlogs - enhance ui

- wardenclyffe/streamlogs/management/commands/google_analytics.py
This job will help backfill mp4 streaming analytics into Wardenclyffe's StreamLog interface, and get all the streaming data (flv & mp4) into one searchable interface.
> Google Analytics data ingester

- wardenclyffe/main/models.py
- wardenclyffe/streamlogs/models.py
- wardenclyffe/templates/main/file.html
- wardenclyffe/templates/streamlogs/streamlog_list.html
> Identify all related videos

- media/css/wardenclyffe.css
- wardenclyffe/templates/main/youtube.html
- wardenclyffe/templates/main/youtube_done.html
- wardenclyffe/templates/mediathread/mediathread.html
trying to remove a lot of old cruft
> Cut over to new .css file

- media/css/jquery.tagsinput.css
- wardenclyffe/panopto/tasks.py
- wardenclyffe/templates/main/upload.html
* bootstrap4 styling
* add Panopto Folder ID input form
* remove grant view access step
* switch to password authentication
> Polish upload form

- wardenclyffe/main/models.py
- wardenclyffe/panopto/tasks.py
- wardenclyffe/panopto/views.py
Pre-S3 videos do not have a backing S3 file. Add a task to pull the file over from CUNIX and upload it to Panopto.
> Add pull from cunix task

- requirements.txt
This reverts commit fd5b8459c397689f1ed45691a53979233c3277a3.
> Revert "Update zeep from 2.5.0 to 3.0.0"

- wardenclyffe/main/management/commands/add_swc_metadata.py
- wardenclyffe/panopto/tasks.py
This little management command import data relevant to the social work commons collection.
> Custom metadata importer

- wardenclyffe/panopto/tasks.py
This will be replaced with more rigorous xml manifest creation in pypanopto.
> HTML escaping for description

- wardenclyffe/main/tests/test_views.py
- wardenclyffe/main/views.py
* and add video id to the report
> Panopto report: fix unicode errors

- media/css/wardenclyffe.css
- wardenclyffe/main/models.py
- wardenclyffe/main/views.py
- wardenclyffe/templates/main/search.html
* optimization via select_related & prefetch
* add ability to sort
* add view count from stream logs
* remove tags & modified columns
> Search Refinement

- wardenclyffe/main/views.py
- wardenclyffe/templates/main/surelink_video.html
Picked up from the original surelink sizing.
> Panopto proxy: add minimal frame size

- wardenclyffe/templates/main/surelink_video.html
* fix logo link
* add telephone links to save Nik the trouble.
> Surelink: polish we're sorry screens

- wardenclyffe/main/models.py
- wardenclyffe/templates/base.html
- wardenclyffe/templates/main/video.html
- wardenclyffe/templates/streamlogs/report.html
- wardenclyffe/templates/streamlogs/streamlog_list.html
Link out to the streamlog detail rather than trying to display it inline
> Video view: update streamlog references

- media/css/wardenclyffe.css
- wardenclyffe/templates/main/surelink_video.html
Offer the embed code to allow easier replacement within environments like Canvas.
> Surelink video display: add a footer with the embed code

- wardenclyffe/graphite/tasks.py
> Update S3 usage task to run weekly

- wardenclyffe/main/management/commands/cleanup_s3.py
First pass - Identify videos that are no longer in use, e.g. have no public endpoint like panopto, cuit or youtube. Then, remove the s3 file.
> S3 Cleanup

- wardenclyffe/main/management/commands/cleanup_s3.py
Videos that have both an "uploaded source file (S3)" and one or more "transcoded" files can generally have the "uploaded" file removed after a year or so.
> S3 Cleanup: remove redundant upload files

- requirements.txt
errr...attrs has an attr module which is different from the attr package.
> add attrs dependency, second try

- wardenclyffe/graphite/tasks.py
> Update task signature

- requirements.txt
Reverts ccnmtl/wardenclyffe#1897
> Revert "Update django requirement from <3,==2.2.12 to ==3.1.4"

- wardenclyffe/templates/main/single_upload.html
- wardenclyffe/templates/main/upload.html
- wardenclyffe/templates/mediathread/mediathread.html
Also, use .text() to set text instead of .html().
> Add missing space to Upload Completed message

- wardenclyffe/main/models.py
- wardenclyffe/main/views.py
- wardenclyffe/panopto/tasks.py
* Allow a video to have more than one panopto location
* Choose the latest one when reporting
* Add a session url field to the report.
> Update Panopto Upload Flow

- wardenclyffe/templates/main/dashboard.html
> Surround filter checkboxes with <label>

- requirements.txt
Reverts ccnmtl/wardenclyffe#2491
> Revert ":arrow_up: ccnmtlsettings 1.9.4"

- wardenclyffe/panopto/tasks.py
From: https://github.com/ccnmtl/mediathread/pull/4685
> Add thumbnail fix here as well

- requirements.txt
Reverts ccnmtl/wardenclyffe#2539
> Revert "Bump billiard from 3.6.4.0 to 4.1.0"

- requirements.txt
Reverts ccnmtl/wardenclyffe#2552
> Revert "Bump cryptography from 38.0.3 to 39.0.0"

- requirements.txt
Reverts ccnmtl/wardenclyffe#2554
> Revert "Revert "Bump cryptography from 38.0.3 to 39.0.0""

- package-lock.json
- package.json
Reverts ccnmtl/wardenclyffe#2553
> Revert "Revert "Bump eslint from 8.30.0 to 8.31.0""

- package-lock.json
- package.json
Reverts ccnmtl/wardenclyffe#2877
> Revert "⬆️ Bump eslint from 8.57.0 to 9.0.0"

- wardenclyffe/templates/main/single_upload.html
- wardenclyffe/templates/main/upload.html
- wardenclyffe/templates/mediathread/mediathread.html
This value now needs to be a proper CSS selector value.
> Update file_dom_selector for new django-s3sign

- wardenclyffe/panopto/tasks.py
This call should reference the correct method name
> Correct typo in statsd call

- requirements.txt
- wardenclyffe/celery.py
https://docs.sentry.io/platforms/python/integrations/celery/
> Install sentry with celery extra

- requirements.txt
Debugging panopto upload issue
> Downgrade botocore and boto3 and s3transfer
